import type { Metadata } from "next";
import "./styles/globals.css";
import { inter } from "./styles/fonts";
import TanstackQueryClientProvider from "./providers/query-client-provider";

export const metadata: Metadata = {
  title: "Next App with Zustand and Tanstack",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TanstackQueryClientProvider>{children}</TanstackQueryClientProvider>
      </body>
    </html>
  );
}
