import type { Metadata, Viewport } from "next";
import "../styles/globals.css";
import { inter } from "../styles/fonts";
import { StoreProviderWrapper } from "@/providers/store-provider";
import QueryClientProviderWrapper from "@/providers/query-client-provider";

export const metadata: Metadata = {
  title: "Next App with Zustand and Tanstack",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  initialScale: 1,
  width: "device-width",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProviderWrapper>
          <QueryClientProviderWrapper>{children}</QueryClientProviderWrapper>
        </StoreProviderWrapper>
      </body>
    </html>
  );
}
